name: Deploy to Heroku

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gentle-bayou-11221" #Must be unique in Heroku
          heroku_email: "niilo.korkiakoski@gmail.com""
